[general]
working_directory = "~"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
opacity = 0.85
blur = true
decorations = "None"
padding = { x = 15, y = 10 }

[font]
normal = {family = "GoMono Nerd Font", style = "Regular"}
size = 11
